apiVersion: v1
kind: Pod
metadata:
  name: ckad-sidecar-pod
  
spec:
  containers:
  - name: main-container
    image: nginx:1.16
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-vol   
  - name: sidecar-container
    image: busybox:1.28
    command: ["/bin/sh", "-c"]
    args:
    - >
      while true; do
        date >> /var/log/current-date.log
        sleep 5
      done
    volumeMounts:
    - mountPath: /var/log
      name: my-vol
  volumes:
  - name: my-vol
    emptyDir: {}